### ISSUE TITLE
文档添加顺序说明

### ISSUE THREAD

**Issue by roachsinai** [larva-lang/larva-lang#15]
看文档都是干货，但是希望有时间的话添加的顺序什么的。感谢！

**Comment by roachsinai** [comment]
虽然可以查看wiki提交记录。。

**Comment by maopao-691515082** [comment]
> 看文档都是干货，但是希望有时间的话添加的顺序什么的。感谢！

添加顺序是指？

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/58611170-bd328280-82e0-11e9-90fb-1636631b1cfe.png)

就是文档不知道该先看哪个。

**Comment by maopao-691515082** [comment]
> ![image](https://user-images.githubusercontent.com/9500049/58611170-bd328280-82e0-11e9-90fb-1636631b1cfe.png)
> 
> 就是文档不知道该先看哪个。

噢，你说这个wiki啊，这个其实是做最早版本时候写的blog，从csdn搬过来的，顺序的话可以到原始地址看：http://blog.csdn.net/xtlisk
