### ISSUE TITLE
读取文件的代码

### ISSUE THREAD

**Issue by PFei-He** [larva-lang/larva-lang#16]
2年前star了您的项目，那时没完善，现在再来看。想请教下读取 .lar 后缀文件的代码是哪一个？或者应该问，哪个位置的代码是把 larva 的代码读到编译器中。最近在研究语言的核心，感觉能从您的代码学到不少东西，还望指教～

**Comment by maopao-691515082** [comment]
Module对象的构造方法里找到文件，然后在parse_token_list中读------------------ 原始邮件 ------------------
发件人: "Fay Ho"<notifications@github.com>
发送时间: 2019年11月27日(星期三) 上午9:28
收件人: "larva-lang/larva-lang"<larva-lang@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [larva-lang/larva-lang] 读取文件的代码 (#16)



2年前star了您的项目，那时没完善，现在再来看。想请教下读取 .lar 后缀文&#x4EF6;的代码是哪一个？或者应该问，哪个位置的代码是把 larva 的代码读到编译器中。最近在研究语言的核心，感觉能从您的代码学到不少东西，还望指教～
 
&mdash;
